#=================================================
# Description: Build lede using GitHub Actions
# Lisence: MIT
#=================================================

name: Build lede

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
    paths:
      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  SSH_ACTIONS: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
             
    - name: Clone source code
      run: git clone https://github.com/coolsnowwolf/lede
      
    - name: Update & Install feeds
      run: |
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
          
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true' || contains(github.event.action, 'ssh')
      
    - name: Upload .config
      uses: actions/upload-artifact@master
      with:
        name: lede_config
        path: lede/.config

    - name: Download package
      id: package
      run: |
        cd lede
        make -j8 download V=s
        
    - name: Compile the firmware
      id: compile
      run: |
        cd lede
        make -j1 V=s
      
    - name: Upload bin directory
      uses: actions/upload-artifact@master
      with:
        name: lede_bin
        path: lede/bin
